# Generated by Django 6.0.1 on 2026-03-02 16:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0002_booking_offer_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property Registry', 'verbose_name_plural': 'Property Registries'},
        ),
        migrations.AlterModelOptions(
            name='hotelgallery',
            options={'verbose_name': 'Property Visual', 'verbose_name_plural': 'Property Visuals'},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name': 'Asset Tier', 'verbose_name_plural': 'Asset Tiers'},
        ),
        migrations.AlterModelOptions(
            name='roomphoto',
            options={},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out_date',
            new_name='check_out',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='is_active',
            new_name='is_live',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial Settlement'), ('PAID', 'Fully Settled'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Onboarding In Progress'), ('PENDING', 'Awaiting Executive Audit'), ('REJECTED', 'Action Required'), ('APPROVED', 'System Approved'), ('LIVE', 'Live & Syncing')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='verification_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='activation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='strategy',
            field=models.CharField(choices=[('DIRECT', 'Direct Growth'), ('EARLY', 'Early Trajectory'), ('URGENT', 'Flash Liquidity')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='usage_limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelPro_Nexus.roomcategory'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Payment Verification'), ('CONFIRMED', 'Confirmed & Locked'), ('ARRIVED', 'Guest Arrived'), ('DEPARTED', 'Finalized'), ('CANCELLED', 'Voided')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(verbose_name='Physical Coordinates'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Market Category'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='doc_govt_registration',
            field=models.FileField(blank=True, null=True, upload_to='vault/legal/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='doc_gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vault/legal/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='doc_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='vault/identity/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='govt_reg_number',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id_type',
            field=models.CharField(default='AADHAAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Property Name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='narrative',
            field=models.TextField(blank=True, verbose_name='Executive Narrative'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hotels', to=settings.AUTH_USER_MODEL, verbose_name='Executive Partner'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='media_file',
            field=models.FileField(upload_to='gallery/property/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='room_class',
            field=models.CharField(choices=[('STANDARD', 'Elite Standard'), ('DELUXE', 'Executive Deluxe'), ('SUITE', 'Presidential Suite'), ('VILLA', 'Private Villa')], default='STANDARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='media_file',
            field=models.FileField(upload_to='gallery/rooms/'),
        ),
    ]
