# Generated by Django 6.0.1 on 2026-03-08 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0006_alter_customuser_options_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='hotelgallery',
            options={'verbose_name': 'Hotel Image', 'verbose_name_plural': 'Hotel Images'},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name': 'Room Category', 'verbose_name_plural': 'Room Categories'},
        ),
        migrations.AddField(
            model_name='booking',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelPro_Nexus.offer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('DEPARTED', 'Departed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Hotel Type'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Hotel Name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='narrative',
            field=models.TextField(blank=True, verbose_name='Hotel Description'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hotels', to=settings.AUTH_USER_MODEL, verbose_name='Hotel Owner'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='strategy',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('EARLY', 'Early Bird'), ('URGENT', 'Flash Sale')], default='DIRECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='room_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite'), ('VILLA', 'Villa')], default='STANDARD', max_length=50),
        ),
    ]
