# Generated by Django 6.0.1 on 2026-03-08 06:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0007_alter_hotel_options_alter_hotelgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Offer & Coupon', 'verbose_name_plural': 'Offers & Coupons'},
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Detailed Description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show on listings? (False = hidden/private coupon)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capped discount value (null for uncapped)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_booking_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum total required to apply this offer', max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='scope',
            field=models.CharField(choices=[('HOTEL', 'Hotel Specific'), ('GLOBAL', 'Platform Wide')], default='HOTEL', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='user_limit',
            field=models.IntegerField(default=1, help_text='Max uses per customer account'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='activation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='HotelPro_Nexus.hotel', verbose_name='Bound Hotel'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Offer Title'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='strategy',
            field=models.CharField(choices=[('GROWTH', 'Growth (New Customers)'), ('URGENCY', 'Urgency (Flash Sale)'), ('LOYALTY', 'Loyalty (Repeat Guests)'), ('SEASONAL', 'Seasonal (Festivals/Holidays)'), ('DIRECT', 'Direct Discount')], default='DIRECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='usage_limit',
            field=models.IntegerField(default=-1, help_text='-1 for unlimited total uses'),
        ),
    ]
