# Generated by Django 6.0.1 on 2026-03-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0008_alter_offer_options_offer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Onboarding In Progress'), ('PENDING', 'Awaiting Executive Audit'), ('REJECTED', 'Action Required'), ('APPROVED', 'System Approved'), ('LIVE', 'Live & Syncing'), ('DELETION_PENDING', 'Decommissioning Under Audit')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='room_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite'), ('VILLA', 'Villa'), ('LUXURY', 'Luxury'), ('ECONOMY', 'Economy'), ('PREMIUM', 'Premium'), ('EXECUTIVE', 'Executive'), ('CLUB', 'Club'), ('PRESIDENTIAL', 'Presidential'), ('ROYAL', 'Royal'), ('FAMILY', 'Family'), ('SPECIALTY', 'Specialty'), ('OTHER', 'Other')], default='STANDARD', max_length=20),
        ),
    ]
