# Generated by Django 6.0.1 on 2026-03-10 16:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0011_offer_targeted_hotels_offer_targeted_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('PRICE', 'Price Discount'), ('STAY', 'Stay Duration'), ('FB', 'Dining & F&B'), ('EXPERIENCE', 'Experience/Activity'), ('PERKS', 'Special Perks')], default='PRICE', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='guest_type',
            field=models.CharField(choices=[('PUBLIC', 'All Guests'), ('MEMBERS', 'Club Members Only'), ('PRIVATE', 'Private Link/Referral')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_nights_stay',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='perks',
            field=models.TextField(blank=True, help_text='Comma-separated perks'),
        ),
        migrations.AddField(
            model_name='offer',
            name='redemption_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='offer',
            name='revenue_generated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='strategy',
            field=models.CharField(choices=[('GROWTH', 'Growth (New Customers)'), ('URGENCY', 'Urgency (Flash Sale)'), ('LOYALTY', 'Loyalty (Repeat Guests)'), ('SEASONAL', 'Seasonal (Festivals/Holidays)'), ('DIRECT', 'Direct Discount'), ('SKIM', 'Skim (Premium Yield Scheme)'), ('CUSTOM', 'Custom (Bespoke Strategy)')], default='DIRECT', max_length=20),
        ),
    ]
