# Generated by Django 6.0.1 on 2026-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0012_offer_category_offer_guest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_stackable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='promotion_type',
            field=models.CharField(choices=[('PERCENT', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount'), ('BOGO', 'Buy One Get One'), ('UPGRADE', 'Free Room Upgrade')], default='PERCENT', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='stay_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='stay_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
