# Generated by Django 6.0.1 on 2026-03-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0013_offer_is_stackable_offer_promotion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='combinable_offers',
            field=models.ManyToManyField(blank=True, help_text='Specific offers this deal can be combined with.', to='HotelPro_Nexus.offer'),
        ),
    ]
