# Generated by Django 6.0.1 on 2026-03-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0014_offer_combinable_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft Strategy'), ('LIVE', 'Live & Active'), ('DISABLED', 'Manually Paused'), ('EXPIRED', 'Naturally Concluded')], default='DRAFT', max_length=15),
        ),
    ]
