# Generated by Django 6.0.1 on 2026-03-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0016_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RoomVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='gallery/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='HotelPro_Nexus.roomcategory')),
            ],
        ),
    ]
