# Generated by Django 6.0.1 on 2026-03-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0017_roomcategory_room_type_roomvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='RoomVideo',
        ),
    ]
