# Generated by Django 6.0.1 on 2026-03-16 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0020_aigloballock_aiauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branched_versions', to='HotelPro_Nexus.aichatmessage'),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ai_theme_mode',
            field=models.IntegerField(default=1, help_text='Sentinel UI Theme (1-5)'),
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Intelligence Session', max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='HotelPro_Nexus.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Session',
                'verbose_name_plural': 'AI Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='HotelPro_Nexus.aichatsession'),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='HotelPro_Nexus.aichatsession'),
        ),
        migrations.CreateModel(
            name='AIDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vault/ai_intel/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('extracted_text', models.TextField(blank=True, help_text='Sanitized text for AI analysis.')),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Analyzing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='HotelPro_Nexus.aichatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Sentinel Document',
                'verbose_name_plural': 'AI Sentinel Documents',
            },
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='attached_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_messages', to='HotelPro_Nexus.aidocument'),
        ),
    ]
