# Generated by Django 6.0.1 on 2026-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0023_remove_aichatsession_intelligence_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='auto_executable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aitask',
            name='category',
            field=models.CharField(choices=[('REVENUE', 'Revenue Optimization'), ('EXPERIENCE', 'Customer Experience'), ('OPERATIONS', 'Operational Efficiency'), ('MARKETING', 'Marketing & Growth'), ('RISK', 'Risk & Alerts')], default='OPERATIONS', max_length=20),
        ),
        migrations.AddField(
            model_name='aitask',
            name='description',
            field=models.TextField(blank=True, help_text='Clear problem statement.'),
        ),
        migrations.AddField(
            model_name='aitask',
            name='metric_value',
            field=models.CharField(blank=True, help_text='Trigger value or impact metric.', max_length=100),
        ),
        migrations.AddField(
            model_name='aitask',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='aitask',
            name='solution',
            field=models.TextField(blank=True, help_text='Suggested actionable solution.'),
        ),
        migrations.AlterField(
            model_name='aitask',
            name='task_type',
            field=models.CharField(choices=[('PRICING', 'Pricing Optimization'), ('OFFER', 'Promotion Activation'), ('VISIBILITY', 'Visibility Adjustment'), ('ALERT', 'Operational Alert'), ('INSIGHT', 'Strategic Recommendation'), ('EXPERIENCE', 'Customer Experience'), ('OPERATIONS', 'Operational Efficiency')], max_length=20),
        ),
    ]
