# Generated by Django 6.0.1 on 2026-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0026_aiemailsupportlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('source', models.CharField(choices=[('chat', 'AI Chatbot'), ('whatsapp', 'WhatsApp'), ('email_form', 'Email Form'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('call', 'Call Button')], db_index=True, default='chat', max_length=20)),
                ('interest_level', models.CharField(choices=[('hot', '🔥 Hot Lead'), ('warm', '⚡ Warm Lead'), ('cold', '❄️ Cold Lead')], db_index=True, default='cold', max_length=10)),
                ('chat_summary', models.TextField(blank=True, verbose_name='Chat Summary')),
                ('followed_up', models.BooleanField(default=False, verbose_name='Followed Up?')),
                ('notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sales Lead',
                'verbose_name_plural': 'Sales Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AIEmailSupportLog',
        ),
    ]
