# Generated by Django 6.0.1 on 2026-03-02 09:45

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('category', models.CharField(max_length=100, verbose_name='Property Category')),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('narrative', models.TextField(blank=True, verbose_name='Property Narrative')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, verbose_name='Cancellation & Business Terms')),
                ('services', models.TextField(blank=True, help_text='JSON array of selected services')),
                ('id_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport')], default='AADHAAR', max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('govt_reg_number', models.CharField(blank=True, max_length=100, verbose_name='Govt. Registration No.')),
                ('gst_number', models.CharField(blank=True, max_length=50, verbose_name='GSTIN')),
                ('doc_id_proof', models.FileField(blank=True, null=True, upload_to='hotels/docs/id/')),
                ('doc_govt_registration', models.FileField(blank=True, null=True, upload_to='hotels/docs/legal/')),
                ('doc_gst_certificate', models.FileField(blank=True, null=True, upload_to='hotels/docs/legal/')),
                ('is_live', models.BooleanField(default=False)),
                ('onboarding_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Registry',
                'verbose_name_plural': 'Hotel Registries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('event', models.CharField(choices=[('REQUEST', 'Reset Requested'), ('SUCCESS', 'Reset Successful'), ('FAILED', 'Validation Failed'), ('EXPIRED', 'Token Expired'), ('INVALID', 'Invalid Token'), ('BLOCKED', 'Rate Limited')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Password Reset Audit',
                'verbose_name_plural': 'Password Reset Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='hotels/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='HotelPro_Nexus.hotel')),
            ],
            options={
                'verbose_name': 'Property Media',
                'verbose_name_plural': 'Property Media Assets',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Deluxe Garden View', max_length=150)),
                ('room_class', models.CharField(choices=[('STANDARD', 'Standard'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite'), ('EXECUTIVE', 'Executive'), ('VILLA', 'Villa'), ('PENTHOUSE', 'Penthouse')], default='STANDARD', help_text='e.g. DELUXE, SUITE', max_length=100)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_count', models.PositiveIntegerField(default=1)),
                ('amenities', models.TextField(blank=True, help_text='JSON array of room-specific amenities')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='HotelPro_Nexus.hotel')),
            ],
            options={
                'verbose_name': 'Room Category',
                'verbose_name_plural': 'Room Categories',
                'ordering': ['hotel', 'room_class'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='hotels/rooms/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='HotelPro_Nexus.roomcategory')),
            ],
            options={
                'verbose_name': 'Room Media Asset',
                'verbose_name_plural': 'Room Media Assets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Enterprise User',
                'verbose_name_plural': 'Enterprise Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hotels', to=settings.AUTH_USER_MODEL, verbose_name='Property Owner'),
        ),
    ]
