# Generated by Django 6.0.1 on 2026-03-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0003_alter_hotel_options_alter_hotelgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HOTEL_ADMIN', 'Hotel Admin'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20, verbose_name='User Role'),
        ),
    ]
