# Generated by Django 6.0.1 on 2026-03-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0005_booking_user_alter_booking_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'System User', 'verbose_name_plural': 'System Users'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='HotelPro_Nexus.hotel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('hotel_admin', 'Hotel Admin'), ('super_admin', 'Super Admin'), ('customer', 'Customer')], db_index=True, default='hotel_admin', max_length=20, verbose_name='System Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='govt_reg_number',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
