# Generated by Django 6.0.1 on 2026-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0010_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='targeted_hotels',
            field=models.ManyToManyField(blank=True, related_name='targeted_offers', to='HotelPro_Nexus.hotel'),
        ),
        migrations.AddField(
            model_name='offer',
            name='targeted_rooms',
            field=models.ManyToManyField(blank=True, related_name='targeted_offers', to='HotelPro_Nexus.roomcategory'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='strategy',
            field=models.CharField(choices=[('GROWTH', 'Growth (New Customers)'), ('URGENCY', 'Urgency (Flash Sale)'), ('LOYALTY', 'Loyalty (Repeat Guests)'), ('SEASONAL', 'Seasonal (Festivals/Holidays)'), ('DIRECT', 'Direct Discount'), ('SKIM', 'Skim (Premium Yield Scheme)')], default='DIRECT', max_length=20),
        ),
    ]
