# Generated by Django 6.0.1 on 2026-03-15 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0018_remove_roomcategory_room_type_delete_roomvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_action_mode_enabled', models.BooleanField(default=False, help_text='Allows AI to automatically trigger promotions and pricing adjustments.', verbose_name='AI Action Mode Enabled')),
                ('last_analysis_at', models.DateTimeField(blank=True, null=True)),
                ('intelligence_level', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='HotelPro_Nexus.hotel')),
            ],
            options={
                'verbose_name': 'AI Agent Configuration',
                'verbose_name_plural': 'AI Agent Configurations',
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_history', to='HotelPro_Nexus.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('metric_value', models.CharField(max_length=100)),
                ('trend_direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], max_length=10)),
                ('narrative', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='HotelPro_Nexus.hotel')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('PRICING', 'Pricing Optimization'), ('OFFER', 'Promotion Activation'), ('VISIBILITY', 'Visibility Adjustment'), ('ALERT', 'Operational Alert'), ('INSIGHT', 'Strategic Recommendation')], max_length=20)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested (Manual Review)'), ('EXECUTED', 'Successfully Executed'), ('FAILED', 'Execution Failed'), ('IGNORED', 'User Dismissed')], default='SUGGESTED', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('reasoning', models.TextField(help_text="The AI's data-driven justification for this task.")),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Metrics used for this decision.')),
                ('impact_estimate', models.CharField(blank=True, help_text="e.g., '+15% Anticipated Yield'", max_length=100)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='HotelPro_Nexus.hotel')),
            ],
            options={
                'verbose_name': 'AI Operational Task',
                'verbose_name_plural': 'AI Operational Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
