# Generated by Django 6.0.1 on 2026-03-16 04:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0019_aiagentconfig_aichatmessage_aiinsight_aitask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGlobalLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_key', models.CharField(max_length=100, unique=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('response_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('execution_trace', models.JSONField(default=dict, help_text='Multi-step agent logic trace.')),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_logs', to='HotelPro_Nexus.hotel')),
            ],
            options={
                'verbose_name': 'AI Audit Log',
                'verbose_name_plural': 'AI Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
