# Generated by Django 6.0.1 on 2026-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0021_sentinel_v4_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='category',
            field=models.CharField(choices=[('STRATEGY', 'Strategic Intelligence'), ('REVENUE', 'Revenue Optimization'), ('OPERATIONS', 'Operational Logistics'), ('GUEST', 'Guest Experience'), ('MARKET', 'Market Analysis'), ('GENERAL', 'General Intelligence')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='intelligence_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stored analysis results for the Intelligence Panel.'),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='personality_mode',
            field=models.CharField(choices=[('SENTINEL', 'Sentinel Analyst'), ('REVENUE', 'Revenue Intelligence AI'), ('OPERATIONS', 'Operations Advisor'), ('GUEST', 'Guest Experience Expert'), ('MARKET', 'Market Intelligence Engine')], default='SENTINEL', max_length=20),
        ),
    ]
