# Generated by Django 6.0.1 on 2026-03-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0022_aichatsession_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatsession',
            name='intelligence_data',
        ),
        migrations.RemoveField(
            model_name='aichatsession',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='aichatsession',
            name='personality_mode',
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='category',
            field=models.CharField(blank=True, default='GENERAL', help_text='Session category tag (e.g. GENERAL, ANALYSIS, TASK)', max_length=50),
        ),
    ]
