# Generated by Django 6.0.1 on 2026-03-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0024_aitask_auto_executable_aitask_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aidocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
