# Generated by Django 6.0.1 on 2026-03-21 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0025_aichatmessage_is_deleted_aichatsession_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmailSupportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('recipient_email', models.EmailField(default='ai-support@hotelpro.com', max_length=254)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Email Support Log',
                'verbose_name_plural': 'AI Email Support Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
