# Generated by Django 6.0.1 on 2026-03-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0027_sales_lead_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='External ID (Meta/Voice)'),
        ),
    ]
