# Generated by Django 6.0.1 on 2026-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelPro_Nexus', '0028_saleslead_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='External ID (Meta/Voice)'),
        ),
    ]
